name: Latest posts workflow - econscience
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "5"
          remove_duplicates: true
          comment_tag_name: "ECONSCIENCE"
          commit_message: "Updated readme with the latest Econscience data"
          feed_list: "https://econscience.org/blog/feed/"
          date_format: "mmm dd, yyyy"
          template: '$date | <a href="$url">$title</a><br>'
          
