name: Latest post workflow - orcasound
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          remove_duplicates: true
          comment_tag_name: "ORCASOUND"
          commit_message: "Updated readme with the latest Orcasound data"
          feed_list: "https://www.orcasound.net/author/scottveirs/feed/"
          date_format: "mmm dd, yyyy"
          template: '$date | <a href="$url">$title</a><br>'
